# -*- coding: utf-8 -*-
"""5_conversao_strings

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6qvdyCzysRUxrtD3wYPEUwnGONIlVXg
"""

#Algoritmo para conversão de strings

import numpy as np

palavra = input("Digite a palavra que você deseja converter: ")

print("A palavra digitada foi: ", palavra)

print("A palavra em caixa alta é: ", palavra.upper())

if (palavra.islower == True):
  print("A palavra já está em caixa baixa: ", palavra)

else:
  print("A palavra em caixa baixa é: ", palavra.lower())

if (type(palavra) == str):
  print("A palavra não possui números")

else:
  palavra_convertida = 0
  palavra_convertida = str(palavra)
  print("A palavra com números, convertida, é: ", palavra_convertida)